// A small subset of countries for example. Use a full list in your app.
// List of { name: "Country Name", code: "ISO Code" }
export const countryList = [
    { name: 'United States', code: 'US' },
    { name: 'India', code: 'IN' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'Germany', code: 'DE' },
    { name: 'France', code: 'FR' },
    { name: 'Canada', code: 'CA' },
    { name: 'Australia', code: 'AU' },
    { name: 'Brazil', code: 'BR' },
    { name: 'China', code: 'CN' },
    { name: 'Japan', code: 'JP' },
    { name: 'Russia', code: 'RU' },
    { name: 'South Korea', code: 'KR' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Italy', code: 'IT' },
    { name: 'Spain', code: 'ES' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Vietnam', code: 'VN' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Egypt', code: 'EG' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'Argentina', code: 'AR' },
];
